sources:
  - name: job_ads                          ← första argumentet i source()
    schema: staging
    tables:
      - name: stg_ads                      ← andra argumentet i source()
        identifier: technical_field_job_ads   ← det riktiga tabellnamnet i Snowflake